### ISSUE TITLE
similar projects / further content

### ISSUE THREAD

**Issue by sarah-jay-peper** [socrates-conference/craft-bok#14]
- https://github.com/softwarecrafters/awesome-software-crafting
- https://github.com/joebew42/study-path

**Comment by brachetti** [comment]
Thanks for the hints @jasontrublu !

how would you prefer we incorporate those? I can think of several ways, but it's probably better to ask for your intentions and ideas on this :)

**Comment by sarah-jay-peper** [comment]
I'm not sure, just wanted to drop this here, as I just had remembered that similar projects exist

**Comment by brachetti** [comment]
Closing this, thanks for bringing it up!
