### ISSUE TITLE
RFC: Pair Programming

### ISSUE THREAD

**Issue by brachetti** [socrates-conference/craft-bok#8]
We would need a showcase content for Pair Programming.

**Comment by Riggs333** [comment]
Origin: Practice of Extreme Programming

# Resources
* [The Art of Agile Development: Pair Programming](https://www.jamesshore.com/Agile-Book/pair_programming.html) (Book chapter)
* [Agile Alliance Glossary: Pair Programming](https://www.agilealliance.org/glossary/pairing)
* [Etiquette for Pair Programming](https://dzone.com/articles/etiquette-for-pair-programming)

# Relations
* Mob Programming

**Comment by Riggs333** [comment]
I'd like to add a link to at least one **video resource** shortly explaining Pair Programming.
Here are two links by code.org as a starting point that I find pretty well done:

* https://www.youtube.com/watch?v=vgkahOzFH2Q
* https://www.youtube.com/watch?v=q7d_JtyCq1A
